### ISSUE TITLE
build an EXE bundle for windows

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#305]
The setup experience is not the best right now, especially on Windows. There are some tools, like https://pyinstaller.org/en/stable/index.html, that can bundle a Python runtime and modules into a single EXE or folder with an EXE.

- [x] make sure all necessary files and folders are created or included
  - [x] extras.json
  - [x] params.json
  - [x] models
  - [x] outputs
  - [x] gfpgan stuff: #315 
- [x] script/automate building the bundle
  - [x] build the bundle
  - [ ] upload to nexus server

**Comment by ssube** [comment]
This seems to be working, using PyInstaller and https://github.com/ssube/onnx-web/blob/main/exe/win10.directml.dir.spec, and I'm working on uploading the bundle and writing docs.

**Comment by ForserX** [comment]
I can offer you the following: to build a startup file on the same C++ with the ability to install dependencies, if there are none, and to run with a commandline.

**Comment by ssube** [comment]
What do you have in mind? We should chat. The bundle that I was able to build with PyInstaller runs as a commandline, but it doesn't install any dependencies.

I've been looking through the options that are available for this, https://pypi.org/project/tufup/ looks interesting but has some setup and requires code changes, where as an installer like NSIS or Inno does not require code changes and could help with updates.

**Comment by ForserX** [comment]
Okay. Come on, I'll try to write you a small C++ script over the weekend, which will run at least under FreeBSD. I'll leave with examples of how and what to edit.

**Comment by ssube** [comment]
I know some C++, enough to be dangerous, and my only concern with it would be debugging - building and bundling that should not be too hard.

I've been debating if/how to package things for Linux. I am familiar with building apt and rpm packages, but I don't really want to run a repository for those. Windows has too many options.

**Comment by ssube** [comment]
I have a v0.10 release candidate bundle, which has a few warnings/errors:

![image](https://user-images.githubusercontent.com/451959/232307838-9dee7662-096f-48a3-a0b9-ded6ec037b62.png)

- #315 
- codeformer import error with PyTorch 2.x
