### ISSUE TITLE
get progress for upscaling and chain pipelines

### ISSUE THREAD

**Issue by ssube** [ssube/onnx-web#90]
Include upscaling in the progress bar, which requires calculating progress for chain pipelines (which wraps upscaling and correction).

Upscaling will need to account for the number of tiles and steps per tile, which should not be too difficult.

Chain pipelines will need to account for each stage, which could have tiles. For the initial version, it might be enough to indicate which stage the pipeline is on, because calculating the number of tiles in the later stages will be difficult (based on the previous stage's input size and outscale).

**Comment by bzlibby** [comment]
this is also missing on inpainting

**Comment by ssube** [comment]
That makes sense, inpainting uses the same code path as outpainting, upscaling, etc: https://github.com/ssube/onnx-web/blob/v0.6.1/api/onnx_web/diffusion/run.py#L159

I'm hoping that fixing this for chain pipelines fixes it everywhere.

**Comment by ssube** [comment]
This is partially fixed, enough that it provides accurate feedback to the user:

![image](https://user-images.githubusercontent.com/451959/218332416-f5534902-a490-4f53-8ef2-1343e7591790.png)

Any chained pipelines, including inpaint, outpaint, and upscaling, should continue to accumulate progress. When the number of steps exceeds the original estimate, currently the steps parameter, the progress spinner will switch to an `N of many` display.

Estimating the number of total steps will come later: https://github.com/ssube/onnx-web/issues/129
